# Generated by Django 2.0.5 on 2018-05-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_mainclass', models.TextField(blank=True, null=True)),
                ('uuid', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('complete', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('visited', models.DateTimeField(blank=True, null=True)),
                ('buildid', models.CharField(blank=True, max_length=255, null=True)),
                ('timing', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('script', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessedProgram',
            fields=[
                ('processed_program_id', models.AutoField(primary_key=True, serialize=False)),
                ('mongo_id', models.CharField(blank=True, max_length=45, null=True)),
                ('uuid', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'processed_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessedProject',
            fields=[
                ('processed_project_id', models.AutoField(primary_key=True, serialize=False)),
                ('sha256', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('buildwith', models.CharField(blank=True, max_length=255, null=True)),
                ('mongo_id', models.CharField(blank=True, max_length=45, null=True)),
                ('uuid', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'processed_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessedRepo',
            fields=[
                ('processed_repo_id', models.AutoField(primary_key=True, serialize=False)),
                ('sha256', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('mongo_id', models.CharField(blank=True, max_length=45, null=True)),
                ('uuid', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'processed_repo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessedRun',
            fields=[
                ('processed_run_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('analysis', models.CharField(blank=True, max_length=255, null=True)),
                ('world', models.IntegerField(blank=True, null=True)),
                ('upper', models.IntegerField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('lower', models.IntegerField(blank=True, null=True)),
                ('difference', models.IntegerField(blank=True, null=True)),
                ('mongo_id', models.CharField(blank=True, max_length=45, null=True)),
                ('uuid', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'processed_run',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawProgram',
            fields=[
                ('raw_program_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mongo_id', models.CharField(blank=True, max_length=45, null=True)),
                ('uuid', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'raw_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawProject',
            fields=[
                ('raw_project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=245, null=True)),
                ('subfolder', models.CharField(blank=True, max_length=255, null=True)),
                ('javaversion', models.CharField(blank=True, max_length=255, null=True)),
                ('mongo_id', models.CharField(blank=True, max_length=45, null=True)),
                ('uuid', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'raw_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawRepo',
            fields=[
                ('raw_repo_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_cls', models.CharField(blank=True, db_column='_cls', max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('rev', models.CharField(blank=True, max_length=255, null=True)),
                ('mongo_id', models.CharField(blank=True, max_length=45, null=True)),
                ('uuid', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'raw_repo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawRun',
            fields=[
                ('raw_run_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('args', models.CharField(blank=True, max_length=255, null=True)),
                ('stdin', models.CharField(blank=True, max_length=255, null=True)),
                ('mongo_id', models.CharField(blank=True, max_length=45, null=True)),
                ('uuid', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'raw_run',
                'managed': False,
            },
        ),
    ]
