version: '2'
services:
  
  db:
    container_name: mysql_database
    image: mysql/mysql-server
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'njr_v2'
    volumes:
      - ./data:/var/lib/mysql

  njr_server:
    container_name: njr_server
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/njr
    ports:
      - "8000:8000"
    depends_on:
      - db
